# Generated by Django 5.2.12 on 2026-03-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('diretor', models.CharField(max_length=255)),
                ('ano_lancamento', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('nota_imdb', models.FloatField()),
            ],
        ),
    ]
