# Generated by Django 5.2.12 on 2026-03-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('LAN', 'Lançamento'), ('CLA', 'Clássico'), ('CUL', 'Cult')], default='CLA', max_length=3),
        ),
    ]
